export const GET_TRENDING = 'GET_TRENDING';
export const GET_TRENDING_FAILED = 'GET_TRENDING_FAILED';
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS';
export const SEARCH_GIFS = 'SEARCH_GIFS';
export const SEARCH_GIF_SUCCESS = 'SEARCH_GIF_SUCCESS';
export const SEARCH_GIF_FAILED = 'SEARCH_GIF_FAILED';
